apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
resources:
- config-map.yaml
- ../../base
#demo patches json6902 replace dev
patches:
- patch: "- op: replace\n  path: /spec/replicas\n  value: 8\n  "
  target:
    kind: Deployment
    name: nginx-api
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0
      value:
        name: newnametest
        image: httpd:alpine
  target:
    kind: Deployment
    name: nginx-api
