apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
- config-map.yaml
- ../../base
components:
- ../../components/external_db
- ../../components/cache
#patch json6902 demo replace
patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 10
  target:
    kind: Deployment
    name: nginx-api
- patch: |-
    - op: add
      path: /spec/template/spec/containers/-
      value:
        name: logstash-mesh
        image: logstash:latest
  target:
    kind: Deployment
    name: nginx-api
